import { readFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const run=(args)=>{const r=spawnSync(process.execPath,args,{stdio:'inherit'});assert.equal(r.status,0,`검사 실패: ${args.join(' ')}`);};
run(['--check','web/app.js']);
run(['--check','web/quick.js']);
run(['--check','web/mapping.js']);
run([resolve(dirname(createRequire(import.meta.url).resolve('typescript/package.json')),'bin/tsc'),'--noEmit']);
assert.equal(fileURLToPath(import.meta.resolve('@hwpx-studio/engine')),resolve('../../packages/hwpx-engine/src/index.ts'),'공통 엔진 경로');
const hashes=JSON.parse(readFileSync('vendor/provenance.json','utf8'));
for(const [file,hash] of Object.entries(hashes.files).filter(([file])=>file.startsWith('rhwp/'))) assert.equal(createHash('sha256').update(readFileSync(resolve('vendor',file))).digest('hex'),hash,`재사용 원본 변경: ${file}`);
const app=['web/app.js','web/quick.js','web/mapping.js'].map(file=>readFileSync(file,'utf8')).join('\n');
assert(!/\.(?:toHwpx|insertText|insertParagraph|setFieldText|deleteText|applyCharFormat|save)\(/.test(app),'RHWP 편집 API 사용 금지');
assert(!/\b(?:eval|Function)\s*\(/.test(readFileSync('src/core.ts','utf8')),'조건의 코드 실행 금지');
console.log(`PASS: 구문·TypeScript·공통 엔진 연결·RHWP ${Object.keys(hashes.files).filter(f=>f.startsWith('rhwp/')).length}파일 해시·읽기 전용 뷰어 경계`);
